language: cpp

compiler: clang

sudo: false

addons:
    apt:
        sources: ubuntu-toolchain-r-test
        packages:
          - g++-4.8
          - clang-3.6

before_install:
  - mkdir build
  - cd build

install:
  - cmake -G "Unix Makefiles" ..
  - make

script: test/libparser_tests
after_success: coveralls