language: cpp

compiler: clang

sudo: false

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - g++-4.8
          - clang-3.6

before_install:
  - g++ -v
  - clang++ -v
  - mkdir build
  - cd build
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi

install:
  - cmake -G "Unix Makefiles" ..
  - make

script: test/libparser_tests
after_success: coveralls