language: cpp

compiler: clang

sudo: required

before_install:
  - sudo apt-get upgrade gcc
  - sudo apt-get upgrade clang
  - mkdir build
  - cd build

install:
  - cmake -G "Unix Makefiles" ..
  - make

script: test/libparser_tests
after_success: coveralls