language: cpp

compiler: clang

sudo: false

addons:
  apt:
    packages:
    - gcc-4.8

before_install:
  - mkdir build
  - cd build

install:
  - cmake -G "Unix Makefiles" ..
  - make

script: test/libparser_tests
after_success: coveralls