language: cpp

compiler: clang

sudo: required

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - g++-4.8
          - clang-3.6

before_install:
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi
  - sudo pip install cpp-coveralls

install:
  - mkdir build && cd build && cmake -G "Unix Makefiles" -DADD_COVERAGE_INFO=1 .. && make

script: test/libparser_tests
after_success:
  - coveralls -b src -r .. --exclude test --gcov-options '\-lp \-b \-c'